### ISSUE TITLE
pybdf

### ISSUE THREAD

**Issue by dhananjay1710** [MAFEMV/Vital-RPPG#1]
First of all, really amazing compilation of code and runs super smoothly on my local machine and colab but:

Installing pybdf on azure is throwing an error saying 'no module named numpy' even though numpy is a part of the requirements.txt file and is also being isntalled separately.

I just need the code till the bpm part, is it possible to extract the code till there and not use pybdf? or if not could you tell me a fix for the pybdf?

**Comment by MAFEMV** [comment]
Hi, as I haven't used it on azure I don't know the reason for that error, if you have the library it should be ok. While i've been running the project locally in python, i haven't present any trouble with pybdf.
To extract the final value of  pulse you need to make a mean of the array bpmES, in there i'm using np.mean. If you find other way to extract the mean, feel free to do it. 
Sorry I can't help you with the pybdf error.
Cheers...

**Comment by dhananjay1710** [comment]
oh okay, thanks man! one last help, could u guide me as to where this mean is being extracted?

**Comment by MAFEMV** [comment]
Hi, I just realized that in main script (test1) numpy is not used for extract the BPM, but it is used in others scripts with functions that are call in main. I can't tell you where pybdf is used especially because is  not a library that I called and used directly, but it is a dependency of the main libraries that I used (pyvhr and heartpy). Is easier if you can find help to install properly pybdf and numpy because is globally used in the project... 
Anyway, you can access directly to the BPM value  in the variable m['bpm'] as shown in line 59 of the script test1.py.

**Comment by dhananjay1710** [comment]
Right, numpy works fine! its the pybdf tbh! ill look for other solutions, thank you so much for your help! with the issue and the project!
